apiVersion: v1
kind: ConfigMap
metadata:
  generateName: mosquitto-conf-
  namespace: {{ .Values.Namespace }}
  labels:
    app: mosquitto
    mosquitto: {{ .Values.Name }}
data:
  mosquitto.conf: |
    # Port for plaintext communication
    listener 1883
    protocol mqtt

    # Port for websocket communication
    listener 1884
    protocol websockets
    
    # Port and certificates for TLS encrypted communication
    # listener 8883
    # certfile /myuser/server.crt
    # cafile /myuser/ca.crt
    # keyfile /myuser/server.key
    {{if .Values.AuthEnabled}}
    password_file /myuser/passwd
    {{else}}
    allow_anonymous true
    {{end}}
